"""add conversation title

Revision ID: 84bbdd5ddb51
Revises: 2534cf3b66b2
Create Date: 2026-08-31 01:23:55.615004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84bbdd5ddb51'
down_revision: Union[str, Sequence[str], None] = '2534cf3b66b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "conversations",
    sa.Column(
        "title",
        sa.String(length=255),
        nullable=False,
        server_default="New Conversation",
    ),
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'title')
    # ### end Alembic commands ###
