"""add anonymous session created at

Revision ID: ad4ebba4e042
Revises: 0699dde85226
Create Date: 2026-08-31 09:42:22.401012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad4ebba4e042'
down_revision: Union[str, Sequence[str], None] = '0699dde85226'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anonymous_sessions', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anonymous_sessions', 'created_at')
    # ### end Alembic commands ###
